--- #YAML:1.0
name:               Text-Lossy
version:            v0.40.1
abstract:           Lossy text compression
author:
    - Ben Deutsch <ben@bendeutsch.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Exception:  0
    Test::More:       0
resources:
    repository:  https://github.com/bendeutsch/text-lossy
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
